### ISSUE TITLE
Update spacy dependency from 1.7 to 1.8

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_nlu#284]
- Need to investigate the change log to see what is different (https://github.com/explosion/spaCy/releases/).
- update NER fine tuning (there is some new docs on that: https://spacy.io/docs/usage/training-ner)

**Comment by tmbo** [comment]
waiting for explosion/spaCy#999

**Comment by riyadhalnur** [comment]
The fix was pushed it seems [https://github.com/explosion/spaCy/commit/d2436dc17be25b0f3ad220212c542e66c44bb512](https://github.com/explosion/spaCy/commit/d2436dc17be25b0f3ad220212c542e66c44bb512). Let me know if I could be of any help.

**Comment by florianlauer** [comment]
After updating to 1.8.1, when I launch the command : 
`python -m rasa_nlu.server -c config_spacy.json --server_model_dirs=./model_YYYYMMDD-HHMMSS`
I'm still getting this error : 
`ERROR:root:Failed to load model './model_20170426-104959'. Error: 1
Traceback (most recent call last):
  File "rasa_nlu/data_router.py", line 84, in __create_model_store
    interpreter = Interpreter.load(metadata, self.config, self.component_builder)
  File "rasa_nlu/model.py", line 245, in load
    component = component_builder.load_component(component_name, context, model_config, meta)
  File "rasa_nlu/components.py", line 234, in load_component
    component = registry.load_component_by_name(component_name, context, model_config)
  File "rasa_nlu/registry.py", line 89, in load_component_by_name
    return load_component(component_clz, context, config)
  File "rasa_nlu/components.py", line 27, in load_component
    return component_clz.load(*load_args)
  File "rasa_nlu/extractors/spacy_entity_extractor.py", line 103, in load
    ner = EntityRecognizer.load(pathlib.Path(ner_dir), spacy_nlp.vocab)
  File "spacy/syntax/parser.pyx", line 154, in spacy.syntax.parser.Parser.load (spacy/syntax/parser.cpp:6999)
    self = cls(vocab, TransitionSystem=TransitionSystem, model=None, **cfg)
  File "spacy/syntax/parser.pyx", line 177, in spacy.syntax.parser.Parser.__init__ (spacy/syntax/parser.cpp:7370)
    cfg['actions'] = TransitionSystem.get_actions(**cfg)
  File "spacy/syntax/ner.pyx", line 71, in spacy.syntax.ner.BiluoPushDown.get_actions (spacy/syntax/ner.cpp:3906)
    actions[action].append(entity_type)
KeyError: 1
INFO:root:Started http server on port 5000
`

**Comment by tmbo** [comment]
I've updated the spacy dependency to 1.8.2 in the requirements. Nevertheless, it is still possible to use 1.7 (since we removed the NER training there is no issue with the changes from 1.7 to 1.8 anymore).
