### ISSUE TITLE
byte output in interactive learining

### ISSUE THREAD

**Issue by jackfreed** [RasaHQ/rasa_nlu#3091]
**Rasa Core version**:
0.14.0a6

**Python version**: 
Python 3.6.8

**Issue**:
i am getting byte output when using the interactive learning

i attached two screenshots for visuals

byte output:
![wrong](https://user-images.githubusercontent.com/25928101/54557865-70672d00-49bc-11e9-9369-ea448650a0fc.png)

string output:
![right](https://user-images.githubusercontent.com/25928101/54557871-74934a80-49bc-11e9-9bc2-74f94aa89de2.png)

changing **print(table.encode("utf-8"))** to **print(table)** in rasa_core/training/interactive.py does the trick.

**Comment by akelad** [comment]
@jackfreed would you actually be able to submit a PR for this? related issue is https://github.com/RasaHQ/rasa_nlu/issues/3062 as well

**Comment by kschoenrock-iw** [comment]
Will this fix be in the next version of rasa-core?

**Comment by akelad** [comment]
i believe this should be fixed now right @tmbo ?

**Comment by tmbo** [comment]
no I don't think that this is fixed yet, `print(table.encode("utf-8"))` didn't work in all cases and resulted in #3062

**Comment by anuragajoshi** [comment]
The issue still persist. I have upgraded to 0.14.2 of Rasa Core. Attached is the screenshot of chat history. 
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/47201468/57371183-b61bc700-71af-11e9-8f16-03b1254cd107.PNG">
