### ISSUE TITLE
Docker Quick-start: server uses default model instead of trained

### ISSUE THREAD

**Issue by HyperColumn** [RasaHQ/rasa_nlu#913]
**Rasa NLU version** (e.g. `0.7.3`): latest-fullt or `0.11.3-full`

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): docker's default

**Operating system** (windows, osx, ...): docker's default

**Issue**:
when using the step by step quick start on https://hub.docker.com/r/rasa/rasa_nlu/

I do the following:

```
docker run -p 5000:5000 rasa/rasa_nlu:latest-full

curl 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/data/examples/rasa/demo-rasa.json' | \
curl --request POST --header 'content-type: application/json' -d@- --url 'localhost:5000/train?project=test_model&pipeline=keyword'

curl 'http://localhost:5000/parse?q=hello&model=test_model'

```
from the results I can see that it doesn't really use the model trained with the json file. specifically on version "latest" I even see on the server that it uses the default model instead.

```

**Comment by tmbo** [comment]
Your last request should be `curl 'http://localhost:5000/parse?q=hello&project=test_model'` (mind the change of `model` to `project`)

**Comment by tmbo** [comment]
I've updated the readme, the description on ducker hub will be updated with the next build of the containers.

**Comment by HyperColumn** [comment]
it still doesn't work, I do the following:
`sudo docker run -p 5000:5000 rasa/rasa_nlu:0.12.0a2-full`

`curl 'htts://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/data/examples/rasa/demo-rasa.json' | curl --request POST --header 'content-type: application/json' -d@- --url 'localhost:5000/train?project=test_model&pipeline=keyword'`

`curl 'htt://localhost:5000/parse?q=yes&project=test_model'`

gives me  the result:
{
  "intent": {
    "name": null,
    "confidence": 1.0
  },
  "entities": [],
  "text": "yes"
}
but yes was in the training set of 
htts://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/data/examples/rasa/demo-rasa.json
